# Project Deliverable 1

*   190394 - Kamau Mikebrian
*   190501 - Kang'ethe Cynthia
*   184413 - Obwogi Peter


## Dataset Exploration — Personal Finance ML Dataset

**Project description:**
SmartSpend -
Predicts student's expected monthly expenditure to support budgeting decisions.

### Open-source dataset candidates considered

| Dataset | Relevance | Possible ML output |
|---|---|---|
| Personal Finance ML Dataset | Personal finance, income, expenses, savings and credit indicators; 32,424 records | monthly_expenses_usd |
| Student Spending Habits Dataset | 1,000 students with income and category-level spending | Food or derived total expenditure |
| University Students Monthly Expenses | University-student monthly expenditure survey | Monthly expenditure / category spending |
| Financial Transactions Dataset (Expenses & Income) | Anonymized transaction-level income and expense records | Expense category or future spending amount |

### Selected dataset
personal Finance ML Dataset

In [1]:
!pip -q install datasets

In [2]:
#This is to initialise the pandas and the dataset
from datasets import load_dataset
import pandas as pd

dataset = load_dataset("asafmak/personal-finance-ml-dataset", split="train")
df = dataset.to_pandas()

print("Dataset loaded successfully.")
print("Shape:", df.shape)
df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/6.25k [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

synthetic_personal_finance_dataset.csv:   0%|          | 0.00/4.19M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/32424 [00:00<?, ? examples/s]

Dataset loaded successfully.
Shape: (32424, 20)

,user_id,age,gender,education_level,employment_status,job_title,monthly_income_usd,monthly_expenses_usd,savings_usd,has_loan,loan_type,loan_amount_usd,loan_term_months,monthly_emi_usd,loan_interest_rate_pct,debt_to_income_ratio,credit_score,savings_to_income_ratio,region,record_date
0,U00001,56,Female,High School,Self-employed,Salesperson,3531.69,1182.59,367655.03,No,None,0.00,0,0.00,0.00,0.00,430,8.68,Other,2024-01-09
1,U00002,19,Female,PhD,Employed,Salesperson,3531.73,2367.99,260869.10,Yes,Education,146323.34,36,4953.50,13.33,1.40,543,6.16,North America,2022-02-13
2,U00003,20,Female,Master,Employed,Teacher,2799.49,1003.91,230921.21,No,None,0.00,0,0.00,0.00,0.00,754,6.87,Africa,2022-05-12
3,U00004,25,Male,PhD,Employed,Manager,5894.88,4440.12,304815.51,Yes,Business,93242.37,24,4926.57,23.93,0.84,461,4.31,Europe,2023-10-02
4,U00005,53,Female,PhD,Employed,Student,5128.93,4137.61,461509.48,No,None,0.00,0,0.00,0.00,0.00,516,7.50,Africa,2021-08-07

3(a).

In [3]:
#Here we find the number of columns and number of rows found in the dataset
rows, columns = df.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

Number of rows: 32424
Number of columns: 20

3(b)

In [4]:
#Here we find the datatypes found in the dataset
print(df.dtypes)

print("\nDatatype counts:")
print(df.dtypes.value_counts())

user_id                     object
age                          int64
gender                      object
education_level             object
employment_status           object
job_title                   object
monthly_income_usd         float64
monthly_expenses_usd       float64
savings_usd                float64
has_loan                    object
loan_type                   object
loan_amount_usd            float64
loan_term_months             int64
monthly_emi_usd            float64
loan_interest_rate_pct     float64
debt_to_income_ratio       float64
credit_score                 int64
savings_to_income_ratio    float64
region                      object
record_date                 object
dtype: object

Datatype counts:
object     9
float64    8
int64      3
Name: count, dtype: int64

3(c)

In [5]:
#Here we convert to a pandas dataframe and check for null values
null_values = df.isna().sum()
display(null_values.to_frame("Null Values"))

if null_values.sum() == 0:
    print("Conclusion: The dataset is complete; there are no null values.")
else:
    print(f"Conclusion: The dataset is not complete; it contains {null_values.sum()} null values in total.")

                         Null Values
user_id                            0
age                                0
gender                             0
education_level                    0
employment_status                  0
job_title                          0
monthly_income_usd                 0
monthly_expenses_usd               0
savings_usd                        0
has_loan                           0
loan_type                      19429
loan_amount_usd                    0
loan_term_months                   0
monthly_emi_usd                    0
loan_interest_rate_pct             0
debt_to_income_ratio               0
credit_score                       0
savings_to_income_ratio            0
region                             0
record_date                        0

Conclusion: The dataset is not complete; it contains 19429 null values in total.

3(d)

In [6]:
#Here we combine the first 15 rows and last 20 rows and display that dataframe
df_sample = pd.concat(
    [df.head(15), df.tail(20)],
    ignore_index=True
)

print("Shape of df_sample:", df_sample.shape)
display(df_sample)

Shape of df_sample: (35, 20)

,user_id,age,gender,education_level,employment_status,job_title,monthly_income_usd,monthly_expenses_usd,savings_usd,has_loan,loan_type,loan_amount_usd,loan_term_months,monthly_emi_usd,loan_interest_rate_pct,debt_to_income_ratio,credit_score,savings_to_income_ratio,region,record_date
0,U00001,56,Female,High School,Self-employed,Salesperson,3531.69,1182.59,367655.03,No,None,0.00,0,0.00,0.00,0.00,430,8.68,Other,2024-01-09
1,U00002,19,Female,PhD,Employed,Salesperson,3531.73,2367.99,260869.10,Yes,Education,146323.34,36,4953.50,13.33,1.40,543,6.16,North America,2022-02-13
2,U00003,20,Female,Master,Employed,Teacher,2799.49,1003.91,230921.21,No,None,0.00,0,0.00,0.00,0.00,754,6.87,Africa,2022-05-12
3,U00004,25,Male,PhD,Employed,Manager,5894.88,4440.12,304815.51,Yes,Business,93242.37,24,4926.57,23.93,0.84,461,4.31,Europe,2023-10-02
4,U00005,53,Female,PhD,Employed,Student,5128.93,4137.61,461509.48,No,None,0.00,0,0.00,0.00,0.00,516,7.50,Africa,2021-08-07
5,U00006,62,Male,Master,Employed,Student,4051.00,2244.42,194901.41,Yes,Car,407915.25,12,38219.81,22.21,9.43,718,4.01,North America,2025-02-12
6,U00007,22,Female,Master,Student,Accountant,983.69,332.62,37522.56,Yes,Car,296057.60,180,6773.29,26.95,6.89,761,3.18,Asia,2024-06-01
7,U00008,18,Female,Bachelor,Employed,Accountant,6199.29,4503.15,89107.54,No,None,0.00,0,0.00,0.00,0.00,540,1.20,Africa,2024-03-17
8,U00009,49,Female,High School,Self-employed,Doctor,4271.51,3062.12,451923.96,No,None,0.00,0,0.00,0.00,0.00,327,8.82,Africa,2023-05-02
9,U00010,61,Male,Master,Employed,Student,5216.18,4369.36,203320.50,Yes,Education,324197.37,360,6782.37,25.09,1.30,558,3.25,Asia,2024-11-23
10,U00011,26,Female,Master,Employed,Manager,3677.43,2247.92,311546.91,Yes,Education,127703.79,240,1818.01,16.43,0.49,412,7.06,Other,2022-09-02
11,U00012,66,Other,Bachelor,Student,Unemployed,4808.10,1537.78,202875.20,No,None,0.00,0,0.00,0.00,0.00,429,3.52,Other,2025-02-21
12,U00013,61,Male,Bachelor,Employed,Student,2449.33,1804.98,109956.88,No,None,0.00,0,0.00,0.00,0.00,497,3.74,Asia,2024-09-07
13,U00014,65,Female,High School,Employed,Driver,5546.28,3630.24,453101.38,Yes,Car,404941.02,60,10823.31,20.42,1.95,788,6.81,North America,2022-01-15
14,U00015,57,Male,PhD,Employed,Accountant,3286.51,2287.38,323017.91,No,None,0.00,0,0.00,0.00,0.00,301,8.19,North America,2024-06-04
15,U32405,36,Male,Bachelor,Employed,Doctor,4686.28,2317.46,371842.16,No,None,0.00,0,0.00,0.00,0.00,483,6.61,Africa,2022-05-23
16,U32406,39,Female,High School,Unemployed,Manager,4373.73,3222.96,51547.14,No,None,0.00,0,0.00,0.00,0.00,641,0.98,Africa,2024-02-27
17,U32407,65,Male,Bachelor,Employed,Teacher,3420.46,2028.22,123124.23,Yes,Business,380138.40,300,4561.42,13.95,1.33,308,3.00,Asia,2023-02-19
18,U32408,21,Other,Master,Unemployed,Unemployed,8361.47,7014.58,688652.16,No,None,0.00,0,0.00,0.00,0.00,324,6.86,Asia,2022-11-16
19,U32409,34,Other,High School,Employed,Student,4448.20,3537.67,28919.10,Yes,Education,408132.22,300,7581.45,22.20,1.70,627,0.54,North America,2024-05-18
20,U32410,18,Female,Master,Employed,Accountant,4114.65,2360.20,133911.66,No,None,0.00,0,0.00,0.00,0.00,823,2.71,Europe,2021-11-15
21,U32411,28,Male,Master,Employed,Student,6850.01,2689.75,65995.01,No,None,0.00,0,0.00,0.00,0.00,676,0.80,Other,2022-07-11
22,U32412,62,Female,High School,Employed,Teacher,5720.76,3165.72,672013.65,No,None,0.00,0,0.00,0.00,0.00,707,9.79,Europe,2023-08-14
23,U32413,25,Male,Bachelor,Unemployed,Unemployed,4922.40,2861.97,33211.62,No,None,0.00,0,0.00,0.00,0.00,531,0.56,Europe,2021-11-21
24,U32414,24,Male,High School,Self-employed,Accountant,5033.75,3121.68,361571.14,No,None,0.00,0,0.00,0.00,0.00,549,5.99,Africa,2024-10-15
25,U32415,40,Female,Other,Employed,Manager,3736.25,1565.94,386006.46,Yes,Car,401861.22,36,12695.08,8.55,3.40,545,8.61,Africa,2024-02-14
26,U32416,57,Female,PhD,Employed,Engineer,3579.84,2861.06,5003.49,Yes,Car,489624.86,300,3463.69,7.01,0.97,775,0.12,Africa,2022-05-04
27,U32417,59,Male,Master,Employed,Salesperson,2907.16,1119.66,127873.43,No,None,0.00,0,0.00,0.00,0.00,762,3.67,Europe,2024-05-14
28,U32418,35,Female,Bachelor,Unemployed,Accountant,5763.30,3235.06,456106.80,Yes,Education,167226.15,120,3863.38,25.50,0.67,619,6.59,Asia,2025-06-22
29,U32419,60,Male,High School,Employed,Manager,5223.10,3347.34,85547.65,No,None,0.00,0,0.00,0.00,0.00,553,1.36,Europe,2024-11-20
30,U32420,30,Female,High School,Employed,Salesperson,4266.87,1510.82,273669.70,Yes,Car,498400.74,120,6227.54,8.68,1.46,434,5.34,Europe,2024-02-25
31,U32421,51,Female,Master,Employed,Student,5725.78,4965.02,17247.57,Yes,Home,83602.57,12,7605.13,16.50,1.33,453,0.25,North America,2025-06-06
32,U32422,18,Female,Bachelor,Self-employed,Doctor,3282.38,2243.77,22081.21,No,None,0.00,0,0.00,0.00,0.00,391,0.56,Other,2025-07-20
33,U32423,36,Other,High School,Self-employed,Accountant,5035.99,4054.32,524039.88,No,None,0.00,0,0.00,0.00,0.00,596,8.67,Asia,2022-06-07
34,U32424,39,Female,Master,Employed,Engineer,4410.19,2866.47,176985.54,No,None,0.00,0,0.00,0.00,0.00,689,3.34,North America,2023-08-01

## Reference
Miah, A. (n.d.). *Personal finance ML dataset*. Kaggle. https://www.kaggle.com/datasets/miadul/personal-finance-ml-dataset